### ISSUE TITLE
Add a search method

### ISSUE THREAD

**Issue by IonicaBizau** [BibleJS/bible-english#3]
[Here](https://github.com/BibleJS/bible-romanian/blob/52bd5b2557e42ead9dc353fd36cd5bd02c3bbd1f/index.js#L116) is an example. :sparkle:

**Comment by DoubleU23** [comment]
Maybe we could use:

https://github.com/philholden/bible
https://philholden.github.io/bible/json/kjv.json

**Comment by edapm** [comment]
Hi, I think this should be looked into again.
