### ISSUE TITLE
Clash with linux native "bible" cli program

### ISSUE THREAD

**Issue by ghost** [BibleJS/bible-english#4]
There is already a native program in GNU/Linux called "bible" -> https://packages.debian.org/source/sid/bible-kjv
Although the name is 'bible-kjv' because it uses the KJV version Bible, you invoke it by just typing 'bible' in the terminal.
So that, your app clashes with it.
Pleas change you appl to other name or make it to use another command, other than 'bible'
:)

**Comment by IonicaBizau** [comment]
Is there any specific reason why you would use both?

**Comment by OrionRandD** [comment]
Yes. Yours is simpler and would be great to use it as well with 'bible'. 
Please, if you can, install 'bible' from any distro that supports 'apt(-get)' package management like debian, ubuntu, or other debian based distros and play with it. Perhaps you will get a better feeling of what I am trying to explain to you.
sudo apt-get install bible-kjv
The command for getting 'bible' help is '?'
You can just type 'bible' and it will show you an interactive prompt where you can pass the arguments...
